import type { GenerationTask } from "./types";

const now = Date.now();

export const SEED_TASKS: GenerationTask[] = [
  {
    id: "t1",
    prompt: "Неоновый киберпанк-город под дождём, вид сверху",
    type: "image",
    model: "Midjourney v6",
    status: "queued",
    progress: 0,
    createdAt: now - 120_000,
    credits: 80,
  },
  {
    id: "t2",
    prompt: "Дрон-облёт горного озера на рассвете, 5 сек",
    type: "video",
    model: "Kling 3.0",
    status: "queued",
    progress: 0,
    createdAt: now - 90_000,
    credits: 150,
  },
  {
    id: "t3",
    prompt: "Сценарий рекламного ролика для кофейни, 30 секунд",
    type: "text",
    model: "GPT-4o",
    status: "queued",
    progress: 0,
    createdAt: now - 80_000,
    credits: 6,
  },
  {
    id: "t4",
    prompt: "Минималистичный логотип кофейни, бежевые тона",
    type: "image",
    model: "Flux",
    status: "queued",
    progress: 0,
    createdAt: now - 200_000,
    credits: 80,
  },
  {
    id: "t5",
    prompt: "Озвучка приветствия мужским голосом",
    type: "audio",
    model: "ElevenLabs",
    status: "queued",
    progress: 0,
    createdAt: now - 300_000,
    credits: 30,
  },
  {
    id: "t6",
    prompt: "Постер в стиле ретро-футуризм 80-х",
    type: "image",
    model: "Seedream",
    status: "queued",
    progress: 22,
    createdAt: now - 400_000,
    credits: 80,
  },
  {
    id: "t7",
    prompt: "Анимация логотипа, 3 секунды, белый фон",
    type: "video",
    model: "Kling 3.0",
    status: "queued",
    progress: 0,
    createdAt: now - 70_000,
    credits: 200,
  },
  {
    id: "t8",
    prompt: "Фоновая музыка для презентации, lofi стиль, 60 сек",
    type: "audio",
    model: "Suno v4",
    status: "queued",
    progress: 0,
    createdAt: now - 60_000,
    credits: 50,
  },
  {
    id: "t9",
    prompt: "Портрет девушки в стиле импрессионизма",
    type: "image",
    model: "DALL-E 3",
    status: "queued",
    progress: 0,
    createdAt: now - 500_000,
    credits: 80,
  },
  {
    id: "t10",
    prompt: "Перевод текста брошюры с русского на английский",
    type: "text",
    model: "Claude 3.5",
    status: "queued",
    progress: 0,
    createdAt: now - 600_000,
    credits: 12,
  },
];
